services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  streamlit:
    build: ./app
    container_name: front_and_backend_app
    ports:
      - "8501:8501"
    depends_on:
      - db